### ISSUE TITLE
Unrelated

### ISSUE THREAD

**Issue by 0dayCTF** [andrewelick/job-bot#1]
Unrelated, but I am having some issues with the PyTesseract. It's saying "Captcha Failed"  I messed around with system paths etc & even "pip install image". Everything is working amazingly except the imagetester.py

Any help would be appreciated!!!

Thank you

**Comment by SlickStretch** [comment]
Hey sorry about posting this here, but the repo seems to be gone.

Did you ever figure out the issue with the amazon bot throwing up

```
Loading Prizes
Could not load items
```

I tried installing lxml via pip as andrewelick suggested, but no difference.

**Comment by 0dayCTF** [comment]
Hit me up on discord 0day#1337

**Comment by andrewelick** [comment]
Sorry guys I made the repo private for the time being. Turning this thing
into a major project. If y'all would like to be a part of it I'd consider
us becoming a team

**Comment by 0dayCTF** [comment]
Lets do it! I’d love to be a part of it. Do you have a discord? Add me 0day#1337

**Comment by ryanrohypnol** [comment]
I just created a test file, to print the captcha as a string, this is my error!

 

C:\Users\Dark Lamb\Desktop\amazon-giveaway-bot-master>python test.py

Traceback (most recent call last):

  File "C:\Users\Dark Lamb\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pytesseract\pytesseract.py", line 184, in run_tesseract

    proc = subprocess.Popen(cmd_args, **subprocess_args())

  File "C:\Users\Dark Lamb\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 769, in __init__

    restore_signals, start_new_session)

  File "C:\Users\Dark Lamb\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 1172, in _execute_child

    startupinfo)

OSError: [WinError 740] The requested operation requires elevation

 

During handling of the above exception, another exception occurred:

 

Traceback (most recent call last):

  File "test.py", line 12, in <module>

    print(pytesseract.image_to_string(Image.open('captcha.png')))

  File "C:\Users\Dark Lamb\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pytesseract\pytesseract.py", line 309, in image_to_string

    }[output_type]()

  File "C:\Users\Dark Lamb\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pytesseract\pytesseract.py", line 308, in <lambda>

    Output.STRING: lambda: run_and_get_output(*args),

  File "C:\Users\Dark Lamb\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pytesseract\pytesseract.py", line 218, in run_and_get_output

    run_tesseract(**kwargs)

  File "C:\Users\Dark Lamb\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pytesseract\pytesseract.py", line 186, in run_tesseract

    raise TesseractNotFoundError()

pytesseract.pytesseract.TesseractNotFoundError: C:/Program Files (x86)/Tesseract-OCR/tesseract.exe is not installed or it's not in your path

**Comment by SlickStretch** [comment]
I don't have a lot of experience, but I'll help however I can. I know very little python and that's about it for programming.

**Comment by andrewelick** [comment]
We can talk in a bit, i have things I have to do for my job search.  I
don't want to promise anything but i'm willing to sit down and see if we
can work something out.

-Andrew
